#import <Foundation/Foundation.h>
#import "../src/PurrTypeEngine.h"

static NSArray<NSString *> *AlphabeticSuchengCodes(void) {
    NSMutableArray<NSString *> *codes = [NSMutableArray array];
    for (unichar first = 'a'; first <= 'z'; first += 1) {
        [codes addObject:[NSString stringWithFormat:@"%C", first]];
    }

    for (unichar first = 'a'; first <= 'z'; first += 1) {
        for (unichar second = 'a'; second <= 'z'; second += 1) {
            [codes addObject:[NSString stringWithFormat:@"%C%C", first, second]];
        }
    }
    return codes;
}

int main(int argc, const char *argv[]) {
    (void)argc;
    (void)argv;

    @autoreleasepool {
        NSString *root = [[NSFileManager defaultManager] currentDirectoryPath];
        NSString *cangjieDirectory = [root stringByAppendingPathComponent:@"third_party/rime-cangjie"];
        NSString *pinyinPath = [root stringByAppendingPathComponent:@"resources/pinyin_seed.tsv"];
        PurrTypeEngine *engine = [[PurrTypeEngine alloc] initWithCangjieDirectory:cangjieDirectory
                                                                            pinyinPath:pinyinPath];

        printf("# code\tcandidate1\tcandidate2\t...\n");
        printf("# Generated by: make update-sucheng-snapshot\n");
        printf("# Locks Quick Classic Sucheng first-page ordering for alphabetic one/two-key codes.\n");
        for (NSString *code in AlphabeticSuchengCodes()) {
            NSArray<MKCandidate *> *candidatePool = [engine candidatesForInput:code limit:100 mode:MKInputModeSucheng];
            NSMutableArray<MKCandidate *> *candidates = [NSMutableArray arrayWithCapacity:9];
            for (MKCandidate *candidate in candidatePool) {
                if (candidate.weight < 0) {
                    continue;
                }
                [candidates addObject:candidate];
                if (candidates.count >= 9) {
                    break;
                }
            }
            if (candidates.count == 0) {
                continue;
            }

            printf("%s", code.UTF8String);
            for (MKCandidate *candidate in candidates) {
                printf("\t%s", candidate.text.UTF8String);
            }
            printf("\n");
        }
    }
    return 0;
}
